# Generated by Django 5.0 on 2023-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='monthly_rent_date',
            field=models.CharField(max_length=255),
        ),
    ]
