# Generated by Django 5.0 on 2023-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
